version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: products_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: products_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin1234
    ports:
      - '5000:3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
